//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogViewer.Properties.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/PCL-Community/PCL2-Log-Viewer.
        /// </summary>
        public static string AppRepository {
            get {
                return ResourceManager.GetString("AppRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCL2 Log Viewer.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file....
        /// </summary>
        public static string ButtonOpenFile {
            get {
                return ResourceManager.GetString("ButtonOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect... (Not implemented).
        /// </summary>
        public static string ButtonStartConnection {
            get {
                return ResourceManager.GetString("ButtonStartConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open URL.
        /// </summary>
        public static string ErrorFailedOpenUrl {
            get {
                return ResourceManager.GetString("ErrorFailedOpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read file.
        /// </summary>
        public static string ErrorFailedReadFile {
            get {
                return ResourceManager.GetString("ErrorFailedReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no default browser..
        /// </summary>
        public static string ErrorNoDefaultBrowser {
            get {
                return ResourceManager.GetString("ErrorNoDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string MenuWindow {
            get {
                return ResourceManager.GetString("MenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string OptionAbout {
            get {
                return ResourceManager.GetString("OptionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All _Windows.
        /// </summary>
        public static string OptionAllWindows {
            get {
                return ResourceManager.GetString("OptionAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connect....
        /// </summary>
        public static string OptionConnect {
            get {
                return ResourceManager.GetString("OptionConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string OptionCopy {
            get {
                return ResourceManager.GetString("OptionCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string OptionExit {
            get {
                return ResourceManager.GetString("OptionExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find....
        /// </summary>
        public static string OptionFind {
            get {
                return ResourceManager.GetString("OptionFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string OptionOpen {
            get {
                return ResourceManager.GetString("OptionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Recent.
        /// </summary>
        public static string OptionOpenRecent {
            get {
                return ResourceManager.GetString("OptionOpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Replace....
        /// </summary>
        public static string OptionReplace {
            get {
                return ResourceManager.GetString("OptionReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _GitHub Repository.
        /// </summary>
        public static string OptionRepository {
            get {
                return ResourceManager.GetString("OptionRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string OptionSave {
            get {
                return ResourceManager.GetString("OptionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string OptionSaveAll {
            get {
                return ResourceManager.GetString("OptionSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a Copy....
        /// </summary>
        public static string OptionSaveCopy {
            get {
                return ResourceManager.GetString("OptionSaveCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _All.
        /// </summary>
        public static string OptionSelectAll {
            get {
                return ResourceManager.GetString("OptionSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett_ings....
        /// </summary>
        public static string OptionSettings {
            get {
                return ResourceManager.GetString("OptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Main Window.
        /// </summary>
        public static string OptionShowMainWindow {
            get {
                return ResourceManager.GetString("OptionShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        public static string OptionWindowCloseAll {
            get {
                return ResourceManager.GetString("OptionWindowCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all windows and activate the main window.
        /// </summary>
        public static string OptionWindowCloseAllTip {
            get {
                return ResourceManager.GetString("OptionWindowCloseAllTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close Current.
        /// </summary>
        public static string OptionWindowCloseCurrent {
            get {
                return ResourceManager.GetString("OptionWindowCloseCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current window.
        /// </summary>
        public static string OptionWindowCloseCurrentTip {
            get {
                return ResourceManager.GetString("OptionWindowCloseCurrentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma_ximize.
        /// </summary>
        public static string OptionWindowMaximize {
            get {
                return ResourceManager.GetString("OptionWindowMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min_imize.
        /// </summary>
        public static string OptionWindowMinimize {
            get {
                return ResourceManager.GetString("OptionWindowMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        public static string SettingLogLevel {
            get {
                return ResourceManager.GetString("SettingLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string SettingShowModules {
            get {
                return ResourceManager.GetString("SettingShowModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string TextExceptionThrown {
            get {
                return ResourceManager.GetString("TextExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string TextLoading {
            get {
                return ResourceManager.GetString("TextLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files.
        /// </summary>
        public static string TextLogFileType {
            get {
                return ResourceManager.GetString("TextLogFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has been thrown, please open an issue on our GitHub repository to report the problem..
        /// </summary>
        public static string TextReportUnhandledException {
            get {
                return ResourceManager.GetString("TextReportUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string TextSaveFile {
            get {
                return ResourceManager.GetString("TextSaveFile", resourceCulture);
            }
        }
    }
}
